---

name: build-check
on: [push, pull_request]
jobs:
  lint:
    name: lint
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        go:
          - '1.17.1'
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.41.1
          args: --timeout 5m
          skip-go-installation: true
  test-and-build:
    name: Test and build on Go ${{ matrix.go }}
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        go:
          - '1.17.1'
    services:
      mysql:
        image: mysql:8.0.26
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: ortelius_test
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}

      - name: Test binary build
        run: go build cmds/orteliusd/orteliusd.go

      - name: Migrate the database
        run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.11.0/migrate.linux-amd64.tar.gz | tar xvz
          ./migrate.linux-amd64 -path=services/db/migrations/ -database "mysql://root:password@tcp(127.0.0.1:3306)/ortelius_test" up

      - name: Run tests
        run: make tests

